#!/bin/bash
module load gcc/8.2.0 python_gpu/3.9.9

export HTTP_PROXY=http://proxy.ethz.ch:3128
export HTTPs_PROXY=http://proxy.ethz.ch:3128

sbatch --time 5-0 --ntasks=4 --mem-per-cpu=8G --gpus=rtx_2080_ti:1  --wrap "PYTHONPATH=/cluster/home/bgunders/deeplearningproject /cluster/scratch/bgunders/conda_envs/sg3exl/bin/python3.9 main.py --variant mixup_gan --dataset cifar10 --optim sgd --epochs 270 --batch_size 32 --learning_rate 0.1 --momentum 0.9 --weight_decay 0.0001 --gamma 0.1 --augment none --random_seed 42"
sbatch --time 5-0 --ntasks=4 --mem-per-cpu=8G --gpus=rtx_2080_ti:1  --wrap "PYTHONPATH=/cluster/home/bgunders/deeplearningproject /cluster/scratch/bgunders/conda_envs/sg3exl/bin/python3.9 main.py --variant mixup_gan --dataset cifar10 --optim sgd --epochs 270 --batch_size 32 --learning_rate 0.1 --momentum 0.9 --weight_decay 0.0001 --gamma 0.1 --augment none --random_seed 4711"
sbatch --time 5-0 --ntasks=4 --mem-per-cpu=8G --gpus=rtx_2080_ti:1  --wrap "PYTHONPATH=/cluster/home/bgunders/deeplearningproject /cluster/scratch/bgunders/conda_envs/sg3exl/bin/python3.9 main.py --variant mixup_gan --dataset cifar10 --optim sgd --epochs 270 --batch_size 32 --learning_rate 0.1 --momentum 0.9 --weight_decay 0.0001 --gamma 0.1 --augment none --random_seed 314159"
sbatch --time 5-0 --ntasks=4 --mem-per-cpu=8G --gpus=rtx_2080_ti:1  --wrap "PYTHONPATH=/cluster/home/bgunders/deeplearningproject /cluster/scratch/bgunders/conda_envs/sg3exl/bin/python3.9 main.py --variant mixup_gan --dataset cifar10 --optim sgd --epochs 270 --batch_size 32 --learning_rate 0.1 --momentum 0.9 --weight_decay 0.0001 --gamma 0.1 --augment cifar10 --random_seed 42"
sbatch --time 5-0 --ntasks=4 --mem-per-cpu=8G --gpus=rtx_2080_ti:1  --wrap "PYTHONPATH=/cluster/home/bgunders/deeplearningproject /cluster/scratch/bgunders/conda_envs/sg3exl/bin/python3.9 main.py --variant mixup_gan --dataset cifar10 --optim sgd --epochs 270 --batch_size 32 --learning_rate 0.1 --momentum 0.9 --weight_decay 0.0001 --gamma 0.1 --augment cifar10 --random_seed 4711"
sbatch --time 5-0 --ntasks=4 --mem-per-cpu=8G --gpus=rtx_2080_ti:1  --wrap "PYTHONPATH=/cluster/home/bgunders/deeplearningproject /cluster/scratch/bgunders/conda_envs/sg3exl/bin/python3.9 main.py --variant mixup_gan --dataset cifar10 --optim sgd --epochs 270 --batch_size 32 --learning_rate 0.1 --momentum 0.9 --weight_decay 0.0001 --gamma 0.1 --augment cifar10 --random_seed 314159"
sbatch --time 5-0 --ntasks=4 --mem-per-cpu=8G --gpus=rtx_2080_ti:1  --wrap "PYTHONPATH=/cluster/home/bgunders/deeplearningproject /cluster/scratch/bgunders/conda_envs/sg3exl/bin/python3.9 main.py --variant mixup --dataset cifar10 --optim sgd --epochs 270 --batch_size 32 --learning_rate 0.1 --momentum 0.9 --weight_decay 0.0001 --gamma 0.1 --augment none --random_seed 42"
sbatch --time 5-0 --ntasks=4 --mem-per-cpu=8G --gpus=rtx_2080_ti:1  --wrap "PYTHONPATH=/cluster/home/bgunders/deeplearningproject /cluster/scratch/bgunders/conda_envs/sg3exl/bin/python3.9 main.py --variant mixup --dataset cifar10 --optim sgd --epochs 270 --batch_size 32 --learning_rate 0.1 --momentum 0.9 --weight_decay 0.0001 --gamma 0.1 --augment none --random_seed 4711"
sbatch --time 5-0 --ntasks=4 --mem-per-cpu=8G --gpus=rtx_2080_ti:1  --wrap "PYTHONPATH=/cluster/home/bgunders/deeplearningproject /cluster/scratch/bgunders/conda_envs/sg3exl/bin/python3.9 main.py --variant mixup --dataset cifar10 --optim sgd --epochs 270 --batch_size 32 --learning_rate 0.1 --momentum 0.9 --weight_decay 0.0001 --gamma 0.1 --augment none --random_seed 314159"
sbatch --time 5-0 --ntasks=4 --mem-per-cpu=8G --gpus=rtx_2080_ti:1  --wrap "PYTHONPATH=/cluster/home/bgunders/deeplearningproject /cluster/scratch/bgunders/conda_envs/sg3exl/bin/python3.9 main.py --variant mixup --dataset cifar10 --optim sgd --epochs 270 --batch_size 32 --learning_rate 0.1 --momentum 0.9 --weight_decay 0.0001 --gamma 0.1 --augment cifar10 --random_seed 42"
sbatch --time 5-0 --ntasks=4 --mem-per-cpu=8G --gpus=rtx_2080_ti:1  --wrap "PYTHONPATH=/cluster/home/bgunders/deeplearningproject /cluster/scratch/bgunders/conda_envs/sg3exl/bin/python3.9 main.py --variant mixup --dataset cifar10 --optim sgd --epochs 270 --batch_size 32 --learning_rate 0.1 --momentum 0.9 --weight_decay 0.0001 --gamma 0.1 --augment cifar10 --random_seed 4711"
sbatch --time 5-0 --ntasks=4 --mem-per-cpu=8G --gpus=rtx_2080_ti:1  --wrap "PYTHONPATH=/cluster/home/bgunders/deeplearningproject /cluster/scratch/bgunders/conda_envs/sg3exl/bin/python3.9 main.py --variant mixup --dataset cifar10 --optim sgd --epochs 270 --batch_size 32 --learning_rate 0.1 --momentum 0.9 --weight_decay 0.0001 --gamma 0.1 --augment cifar10 --random_seed 314159"
sbatch --time 5-0 --ntasks=4 --mem-per-cpu=8G --gpus=rtx_2080_ti:1  --wrap "PYTHONPATH=/cluster/home/bgunders/deeplearningproject /cluster/scratch/bgunders/conda_envs/sg3exl/bin/python3.9 main.py --variant manifold_mixup --dataset cifar10 --optim sgd --epochs 270 --batch_size 32 --learning_rate 0.1 --momentum 0.9 --weight_decay 0.0001 --gamma 0.1 --augment none --random_seed 42"
sbatch --time 5-0 --ntasks=4 --mem-per-cpu=8G --gpus=rtx_2080_ti:1  --wrap "PYTHONPATH=/cluster/home/bgunders/deeplearningproject /cluster/scratch/bgunders/conda_envs/sg3exl/bin/python3.9 main.py --variant manifold_mixup --dataset cifar10 --optim sgd --epochs 270 --batch_size 32 --learning_rate 0.1 --momentum 0.9 --weight_decay 0.0001 --gamma 0.1 --augment none --random_seed 4711"
sbatch --time 5-0 --ntasks=4 --mem-per-cpu=8G --gpus=rtx_2080_ti:1  --wrap "PYTHONPATH=/cluster/home/bgunders/deeplearningproject /cluster/scratch/bgunders/conda_envs/sg3exl/bin/python3.9 main.py --variant manifold_mixup --dataset cifar10 --optim sgd --epochs 270 --batch_size 32 --learning_rate 0.1 --momentum 0.9 --weight_decay 0.0001 --gamma 0.1 --augment none --random_seed 314159"
sbatch --time 5-0 --ntasks=4 --mem-per-cpu=8G --gpus=rtx_2080_ti:1  --wrap "PYTHONPATH=/cluster/home/bgunders/deeplearningproject /cluster/scratch/bgunders/conda_envs/sg3exl/bin/python3.9 main.py --variant manifold_mixup --dataset cifar10 --optim sgd --epochs 270 --batch_size 32 --learning_rate 0.1 --momentum 0.9 --weight_decay 0.0001 --gamma 0.1 --augment cifar10 --random_seed 42"
sbatch --time 5-0 --ntasks=4 --mem-per-cpu=8G --gpus=rtx_2080_ti:1  --wrap "PYTHONPATH=/cluster/home/bgunders/deeplearningproject /cluster/scratch/bgunders/conda_envs/sg3exl/bin/python3.9 main.py --variant manifold_mixup --dataset cifar10 --optim sgd --epochs 270 --batch_size 32 --learning_rate 0.1 --momentum 0.9 --weight_decay 0.0001 --gamma 0.1 --augment cifar10 --random_seed 4711"
sbatch --time 5-0 --ntasks=4 --mem-per-cpu=8G --gpus=rtx_2080_ti:1  --wrap "PYTHONPATH=/cluster/home/bgunders/deeplearningproject /cluster/scratch/bgunders/conda_envs/sg3exl/bin/python3.9 main.py --variant manifold_mixup --dataset cifar10 --optim sgd --epochs 270 --batch_size 32 --learning_rate 0.1 --momentum 0.9 --weight_decay 0.0001 --gamma 0.1 --augment cifar10 --random_seed 314159"
sbatch --time 5-0 --ntasks=4 --mem-per-cpu=8G --gpus=rtx_2080_ti:1  --wrap "PYTHONPATH=/cluster/home/bgunders/deeplearningproject /cluster/scratch/bgunders/conda_envs/sg3exl/bin/python3.9 main.py --variant standard --dataset cifar10 --optim sgd --epochs 270 --batch_size 32 --learning_rate 0.1 --momentum 0.9 --weight_decay 0.0001 --gamma 0.1 --augment none --random_seed 42"
sbatch --time 5-0 --ntasks=4 --mem-per-cpu=8G --gpus=rtx_2080_ti:1  --wrap "PYTHONPATH=/cluster/home/bgunders/deeplearningproject /cluster/scratch/bgunders/conda_envs/sg3exl/bin/python3.9 main.py --variant standard --dataset cifar10 --optim sgd --epochs 270 --batch_size 32 --learning_rate 0.1 --momentum 0.9 --weight_decay 0.0001 --gamma 0.1 --augment none --random_seed 4711"
sbatch --time 5-0 --ntasks=4 --mem-per-cpu=8G --gpus=rtx_2080_ti:1  --wrap "PYTHONPATH=/cluster/home/bgunders/deeplearningproject /cluster/scratch/bgunders/conda_envs/sg3exl/bin/python3.9 main.py --variant standard --dataset cifar10 --optim sgd --epochs 270 --batch_size 32 --learning_rate 0.1 --momentum 0.9 --weight_decay 0.0001 --gamma 0.1 --augment none --random_seed 314159"
sbatch --time 5-0 --ntasks=4 --mem-per-cpu=8G --gpus=rtx_2080_ti:1  --wrap "PYTHONPATH=/cluster/home/bgunders/deeplearningproject /cluster/scratch/bgunders/conda_envs/sg3exl/bin/python3.9 main.py --variant standard --dataset cifar10 --optim sgd --epochs 270 --batch_size 32 --learning_rate 0.1 --momentum 0.9 --weight_decay 0.0001 --gamma 0.1 --augment cifar10 --random_seed 42"
sbatch --time 5-0 --ntasks=4 --mem-per-cpu=8G --gpus=rtx_2080_ti:1  --wrap "PYTHONPATH=/cluster/home/bgunders/deeplearningproject /cluster/scratch/bgunders/conda_envs/sg3exl/bin/python3.9 main.py --variant standard --dataset cifar10 --optim sgd --epochs 270 --batch_size 32 --learning_rate 0.1 --momentum 0.9 --weight_decay 0.0001 --gamma 0.1 --augment cifar10 --random_seed 4711"
sbatch --time 5-0 --ntasks=4 --mem-per-cpu=8G --gpus=rtx_2080_ti:1  --wrap "PYTHONPATH=/cluster/home/bgunders/deeplearningproject /cluster/scratch/bgunders/conda_envs/sg3exl/bin/python3.9 main.py --variant standard --dataset cifar10 --optim sgd --epochs 270 --batch_size 32 --learning_rate 0.1 --momentum 0.9 --weight_decay 0.0001 --gamma 0.1 --augment cifar10 --random_seed 314159"
